spring:
  application:
    name: oauth2-service

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 674418730021-hgo0ir08drl3de29bt2t8ppsv4ppkihn.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
            
            redirect-uri: "http://localhost:9092/login/oauth2/code/google"

          github:
            client-id: Ov23liYr5WDyrCLNzBHK
            client-secret: 75491c0aae2e2c9cf71e45be66a60655359562e2
            scope:
              - user:email
              - read:user
            
            redirect-uri: "http://localhost:9092/login/oauth2/code/github"

  datasource:
    url: jdbc:postgresql://localhost:5432/oauth2_service
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

server:
  port: 9092
