spring:
  application:
    name: oauth2-service

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 674418730021-gnbun306n8jkkephfnhp5epsll6r3sdm.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
            
            redirect-uri: "http://localhost:9092/login/oauth2/code/google"

          github:
            client-id: Ov23liYr5WDyrCLNzBHK
            client-secret: 076ca22fd8a2a56314fc84c213a32b27592934b7
            scope:
              - user:email
              - read:user
            
            redirect-uri: "http://localhost:9092/login/oauth2/code/github"

  datasource:
    url: jdbc:postgresql://localhost:5432/oauth2_service
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

server:
  port: 9092
